# Generated by Django 3.2.8 on 2022-01-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0002_remove_administrativo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
