# Generated by Django 3.2.8 on 2022-02-05 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentario',
        ),
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(max_length=110, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No Publicado'),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=90, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
