# Generated by Django 3.2.8 on 2022-02-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0008_auto_20220205_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='estado',
        ),
    ]
