# Generated by Django 3.2.8 on 2022-02-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0010_alter_post_contenido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reclamo',
        ),
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Publicado/No publicado'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=False, max_length=100, verbose_name='Slug'),
        ),
    ]
