# Generated by Django 3.2.8 on 2022-02-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0011_auto_20220205_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=100, verbose_name='Slug'),
        ),
    ]
