# Generated by Django 3.2.8 on 2022-02-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0012_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.CharField(default='', max_length=110, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Publicado/No Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='', max_length=90, verbose_name='Título'),
        ),
    ]
