# Generated by Django 3.2.8 on 2022-02-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0013_auto_20220205_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='', max_length=90, verbose_name='Autor'),
        ),
    ]
