# Generated by Django 3.2.8 on 2022-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0015_alter_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_user',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
