# Generated by Django 4.0 on 2022-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0019_reclamo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='avatar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
