# Generated by Django 4.0 on 2022-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0021_remove_reclamo_avatar_remove_reclamo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='avatar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='usuario',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
