# Generated by Django 4.0 on 2022-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0022_reclamo_avatar_reclamo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='problema',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reclamo',
            name='resumen',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='detalles',
            field=models.CharField(max_length=200),
        ),
    ]
