# Generated by Django 4.0 on 2022-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0024_reclamo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='identificacion',
            field=models.IntegerField(max_length=100),
        ),
    ]
