# Generated by Django 3.2.8 on 2022-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSinLuz', '0025_alter_reclamo_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='identificacion',
            field=models.IntegerField(),
        ),
    ]
